name: seven
description: "The movie application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Splash
  flutter_native_splash: ^2.4.4

  # UI & State
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.4

  # Networking & http
  http: ^1.2.2
  json_annotation: ^4.8.1

  # Local Storage
  shared_preferences: ^2.2.2

  # Media
#  video_player: ^2.8.2
#  chewie: ^1.7.5

  # Images & UI Enhancement
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0

  #Effects
  carousel_slider: ^5.1.1

  # Utility
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

  # Linting & formatting
  flutter_lints: ^5.0.0

#  dart run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: true

  color: "#131213"
  image: assets/images/playstore.webp

  android_12:
    color: "#131213"
    image: assets/images/android_splash_screen.webp

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/icons/filled_icons/
    - assets/icons/outlined_icons/
    - assets/images/
    - assets/images/genre_cards/back_drop/
    - assets/images/genre_cards/poster/
    - assets/images/avatars/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand.ttf
    - family: staatliches
      fonts:
        - asset: assets/fonts/staatliches.ttf
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
