// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlknjdNQU3AhgTs6Mbyq1v4xzyqJ5VG1E',
    appId: '1:852324756828:web:80f16a77fcfe85432da599',
    messagingSenderId: '852324756828',
    projectId: 'seven-47ee8',
    authDomain: 'seven-47ee8.firebaseapp.com',
    storageBucket: 'seven-47ee8.firebasestorage.app',
    measurementId: 'G-DN209TMYM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_SLtQGqUOoLqLIcIFuo_CSrcZNVJam5U',
    appId: '1:852324756828:android:ab54a09d8f2093622da599',
    messagingSenderId: '852324756828',
    projectId: 'seven-47ee8',
    storageBucket: 'seven-47ee8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb4_gtrlmtM8iDU_yaN6zRuCMTFPsPQoo',
    appId: '1:852324756828:ios:88f794c84098f65e2da599',
    messagingSenderId: '852324756828',
    projectId: 'seven-47ee8',
    storageBucket: 'seven-47ee8.firebasestorage.app',
    iosBundleId: 'com.example.netflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb4_gtrlmtM8iDU_yaN6zRuCMTFPsPQoo',
    appId: '1:852324756828:ios:88f794c84098f65e2da599',
    messagingSenderId: '852324756828',
    projectId: 'seven-47ee8',
    storageBucket: 'seven-47ee8.firebasestorage.app',
    iosBundleId: 'com.example.netflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlknjdNQU3AhgTs6Mbyq1v4xzyqJ5VG1E',
    appId: '1:852324756828:web:92f2c4100a2ee73c2da599',
    messagingSenderId: '852324756828',
    projectId: 'seven-47ee8',
    authDomain: 'seven-47ee8.firebaseapp.com',
    storageBucket: 'seven-47ee8.firebasestorage.app',
    measurementId: 'G-F1H5SL730J',
  );
}
