enum StorageKey {
  FIRST_VISIT,
  PROFILE_PIC_INDEX, //Profile
  NAME,
  GENDER_INDEX,
  DATE_OF_BIRTH,
  TRENDING, // Shows
  TOP_SHOWS,
  NEW_RELEASE,
  UPCOMING,
  ALL_TIME_CLASSIC,
  POPULAR_IN_INDIA,
  POPULAR_TV,
  AIRING_TODAY_TV,
  ON_THE_AIR,
  GENRES
}