enum StorageKey {
  FIRST_VISIT,
  PROFILE_PIC_INDEX,
  NAME,
  GENDER_INDEX,
  DATE_OF_BIRTH,
  TRENDING,
  TOP_20_MOVIES,
  NEW_RELEASE,
  UPCOMING,
  ALL_TIME_CLASSIC,
  POPULAR_IN_INDIA,
  GENRES
}